apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-client.fullname" . }}
  labels:
    {{- include "kubernetes-client.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubernetes-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubernetes-client.selectorLabels" . | nindent 8 }}
        app: {{ include "kubernetes-client.fullname" . }}
        version: {{ .Values.version }}
    spec:
      serviceAccountName: {{ include "kubernetes-client.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
