apiVersion: v1
kind: Service
metadata:
  name: http-kubernetes-example
  labels:
    {{- include "kubernetes-client.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app: {{ include "kubernetes-client.fullname" . }}
    version: {{ .Values.version }}
